
SET NUMERIC_ROUNDABORT OFF
GO
SET ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, ARITHABORT, QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
SET XACT_ABORT ON
GO
SET TRANSACTION ISOLATION LEVEL Serializable
GO
BEGIN TRANSACTION
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Creating [dbo].[T_ACAO]'
GO
CREATE TABLE [dbo].[T_ACAO]
(
[NM_ACAO] [varchar] (100) COLLATE Latin1_General_CI_AS NOT NULL
)
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Creating primary key [PK_ACAO] on [dbo].[T_ACAO]'
GO
ALTER TABLE [dbo].[T_ACAO] ADD CONSTRAINT [PK_ACAO] PRIMARY KEY CLUSTERED  ([NM_ACAO])
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Creating [dbo].[T_ACAO_FUNCIONALIDADE_MES]'
GO
CREATE TABLE [dbo].[T_ACAO_FUNCIONALIDADE_MES]
(
[NM_ACAO] [varchar] (100) COLLATE Latin1_General_CI_AS NOT NULL,
[NM_FNCAO_MES] [varchar] (100) COLLATE Latin1_General_CI_AS NOT NULL
)
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Creating primary key [PK_ACAO_FNCAO_MES] on [dbo].[T_ACAO_FUNCIONALIDADE_MES]'
GO
ALTER TABLE [dbo].[T_ACAO_FUNCIONALIDADE_MES] ADD CONSTRAINT [PK_ACAO_FNCAO_MES] PRIMARY KEY CLUSTERED  ([NM_ACAO], [NM_FNCAO_MES])
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Creating [dbo].[T_FUNCIONALIDADE_MES]'
GO
CREATE TABLE [dbo].[T_FUNCIONALIDADE_MES]
(
[NM_FNCAO_MES] [varchar] (100) COLLATE Latin1_General_CI_AS NOT NULL
)
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Creating primary key [PK_FNCAO_MES] on [dbo].[T_FUNCIONALIDADE_MES]'
GO
ALTER TABLE [dbo].[T_FUNCIONALIDADE_MES] ADD CONSTRAINT [PK_FNCAO_MES] PRIMARY KEY CLUSTERED  ([NM_FNCAO_MES])
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Creating [dbo].[T_PERMISSAO_ACESSO]'
GO
CREATE TABLE [dbo].[T_PERMISSAO_ACESSO]
(
[ID_PERMT_ACSS] [int] NOT NULL,
[CD_GRUPO_AD] [varchar] (100) COLLATE Latin1_General_CI_AS NOT NULL,
[NM_ACAO] [varchar] (100) COLLATE Latin1_General_CI_AS NOT NULL,
[NM_FNCAO_MES] [varchar] (100) COLLATE Latin1_General_CI_AS NOT NULL,
[CD_PLANTA] [varchar] (4) COLLATE Latin1_General_CI_AS NULL,
[ID_PRCS] [int] NULL
)
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Creating primary key [PK_PERMT_ACSS] on [dbo].[T_PERMISSAO_ACESSO]'
GO
ALTER TABLE [dbo].[T_PERMISSAO_ACESSO] ADD CONSTRAINT [PK_PERMT_ACSS] PRIMARY KEY CLUSTERED  ([ID_PERMT_ACSS])
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Adding foreign keys to [dbo].[T_ACAO_FUNCIONALIDADE_MES]'
GO
ALTER TABLE [dbo].[T_ACAO_FUNCIONALIDADE_MES] ADD CONSTRAINT [FK_ACAO_FNCAO_MES_ACAO_01] FOREIGN KEY ([NM_ACAO]) REFERENCES [dbo].[T_ACAO] ([NM_ACAO])
GO
ALTER TABLE [dbo].[T_ACAO_FUNCIONALIDADE_MES] ADD CONSTRAINT [FK_ACAO_FNCAO_MES_FNCAO_MES_01] FOREIGN KEY ([NM_FNCAO_MES]) REFERENCES [dbo].[T_FUNCIONALIDADE_MES] ([NM_FNCAO_MES])
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Adding foreign keys to [dbo].[T_PERMISSAO_ACESSO]'
GO
ALTER TABLE [dbo].[T_PERMISSAO_ACESSO] ADD CONSTRAINT [FK_PERMT_ACSS_ACAO_FNCAO_MES_01] FOREIGN KEY ([NM_ACAO], [NM_FNCAO_MES]) REFERENCES [dbo].[T_ACAO_FUNCIONALIDADE_MES] ([NM_ACAO], [NM_FNCAO_MES])
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
COMMIT TRANSACTION
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
DECLARE @Success AS BIT
SET @Success = 1
SET NOEXEC OFF
IF (@Success = 1) PRINT 'The database update succeeded'
ELSE BEGIN
	IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
	PRINT 'The database update failed'
END
GO


